import NavBar from './component/navBar'
import './globals.css'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Elsewedy',
  description: 'Generated by mahmoud saad',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        <main>
        {children}
        </main>
        </body>
    </html>
  )
}
