import NavBar from './component/navBar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from './component/footer';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Elsewedy',
  description: 'Generated by mahmoud saad',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <head>
        {/* Add the link tag for the favicon */}
        <link rel="icon" href="./public/favicon.ico.png" />
      </head>
      <body suppressHydrationWarning={true} className={inter.className}>
        <NavBar />
         {children}
      <Footer />
        </body>
    </html>
  )
}
